name: CI DevSecOps

on:
  push:
    branches: [ "main" ]

env:
  PYTHON_VERSION: "3.11"
  CONTAINER_IMAGE: ${{ vars.CONTAINER_IMAGE || format('{0}/todo-python', secrets.DOCKERHUB_USERNAME) }}

jobs:
  unit_test:
    name: Unit Test (pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade "setuptools>=78.1.1,<79.0.0"
          pip install -r dev-requirements.txt -r requirements.txt

      - name: Run pytest
        run: PYTHONPATH=. pytest -q


  sast_bandit:
    name: SAST (Bandit)
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run bandit
        run: bandit -r app -f json -o bandit-report.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

  sca:
    name: SCA (pip-audit)
    runs-on: ubuntu-latest
    needs: [sast_bandit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
      - name: Run pip-audit
        run: |
          pip-audit -r requirements.txt -r dev-requirements.txt --strict --progress-spinner=off --format json > pip-audit-report.json
          cat pip-audit-report.json
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: pip-audit-report.json
  
  secret_scan_gitleaks:
    name: Secret Scan (Gitleaks)
    runs-on: ubuntu-latest
    needs: [sca]
    steps:
      - uses: actions/checkout@v4
      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks
      - name: Run Gitleaks
        run: gitleaks detect --source . --report-format json --report-path gitleaks-report.json
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json