name: CI DevSecOps

on:
  push:
    branches: [ "main" ]

env:
  PYTHON_VERSION: "3.11"
  CONTAINER_IMAGE: ${{ vars.CONTAINER_IMAGE || format('{0}/todo-python', secrets.DOCKERHUB_USERNAME) }}

jobs:
  unit_test:
    name: Unit Test (pytest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade "setuptools>=78.1.1,<79.0.0"
          pip install -r dev-requirements.txt -r requirements.txt

      - name: Run pytest
        run: PYTHONPATH=. pytest -q


  sast_bandit:
    name: SAST (Bandit)
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run bandit
        run: bandit -r app -f json -o bandit-report.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit
        run: |
          pip-audit -r requirements.txt
          pip-audit -r dev-requirements.txt